server:
  port: 8080

spring:
  profiles:
    active: default
  application:
    name: school-registration-system
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
    contexts: sql,data
    enabled: true
